[[constraint]]
  name = "github.com/gobuffalo/buffalo"
  version = "0.12.0"

[[constraint]]
  name = "github.com/gobuffalo/envy"
  version = "1.6.3"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "17.3.0"
