apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: git2grid
  namespace: git2grid
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: git2grid
        role: git2grid
    spec:
      containers:
        - name: git2grid
          image: billytrend/git2grid:latest
          ports:
            - containerPort: 3000
          env:
            - name: GO_ENV
              value: "production"
            - name: eventgridEndpoint
              value: "gridfromgit.westus2-1.eventgrid.azure.net"
            - name: webhookSecret
              valueFrom:
                secretKeyRef:
                  name: git2grid-secrets
                  key: webhook-secret
            - name: eventgridSecret
              valueFrom:
                secretKeyRef:
                  name: git2grid-secrets
                  key: eventgrid-secret
---
apiVersion: v1
kind: Service
metadata:
  name: git2grid
  namespace: git2grid
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      name: "http"
  selector:
    app: git2grid
    role: git2grid
